[build]
builder = "dockerfile"

[deploy]
startCommand = "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
NODE_ENV = "production"
